/*
Created by: Gavi
Creation date: 29/07/25
Description: Using Inner JOIN - Invoices generated by specific customers
*/

SELECT
	c.LastName,
	c.FirstName,
	i.InvoiceId,
	i.CustomerId,
	i.InvoiceDate,
	i.total
FROM
	Invoice AS i
INNER JOIN
	Customer AS c
On
	i.CustomerId = c.CustomerId

Order by c.CustomerId